// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:e_commerce_app_bloc/core/services/hive/adapters/cart_product.dart';
import 'package:e_commerce_app_bloc/core/services/hive/adapters/products.dart';
import 'package:e_commerce_app_bloc/core/services/hive/adapters/user_cart.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartProductAdapter());
    registerAdapter(ProductsAdapter());
    registerAdapter(UserCartAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartProductAdapter());
    registerAdapter(ProductsAdapter());
    registerAdapter(UserCartAdapter());
  }
}
